### ISSUE TITLE
Erreur lors du démarrage

### ISSUE THREAD

**Issue by MisterGoodDeal** [Aymkdn/assistant-plugins#16]
Bonjour, lors du lancement du fichier "start.bat", j'obtiens cette erreur apres le "Prêt à écouter les commandes via Pushbullet". Des idées ? 
Merci :D

`[assistant] Prêt à écouter les commandes via PushBullet
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: Server responded with a non-101 status: 401 Unauthorized
Response Headers Follow:
date: Thu, 23 Nov 2017 18:24:31 GMT
content-length: 0
content-type: text/plain; charset=utf-8

    at WebSocketClient.failHandshake (C:\Users\Server-Windows\Desktop\Freebox\node_modules\websocket\lib\WebSocketClient.js:326:32)
    at ClientRequest.<anonymous> (C:\Users\Server-Windows\Desktop\Freebox\node_modules\websocket\lib\WebSocketClient.js:265:18)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)`

**Comment by Aymkdn** [comment]
Vérifie ton Token pour Pushbullet. Il est possible qu'il soit incorrect
