### ISSUE TITLE
Erreur JS

### ISSUE THREAD

**Issue by dmartinpro** [Aymkdn/assistant-plugins#165]
Voici les logs lors d'un déclenchement d'une applet IFTTT ("Alllume la TV" depuis Alexa):
```
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 2287ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=69049337&key=power
[assistant-freebox] Commande « on » exécutée
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'pushes' of undefined
    at /opt/assistant-plugins/node_modules/assistant-plugins/index.js:86:22
    at Promise (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:152:12)
    at new Promise (<anonymous>)
    at PushBullet.handleError (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:149:9)
    at request.(anonymous function).then.catch.err (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:108:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pushes' of undefined
    at /opt/assistant-plugins/node_modules/assistant-plugins/index.js:86:22
    at Promise (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:152:12)
    at new Promise (<anonymous>)
    at PushBullet.handleError (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:149:9)
    at request.(anonymous function).then.catch.err (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:108:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 4)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pushes' of undefined
    at /opt/assistant-plugins/node_modules/assistant-plugins/index.js:86:22
    at Promise (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:152:12)
    at new Promise (<anonymous>)
    at PushBullet.handleError (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:149:9)
    at request.(anonymous function).then.catch.err (/opt/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:108:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 6)
```

**Comment by Aymkdn** [comment]
Je viens de publier la version 2.0.5 d'`assistant-plugins` qui devrait afficher le "vrai" message d'erreur dans ton cas (personne n'a eu ça auparavant). Je t'invite donc à le mettre à jour et à retester
