### ISSUE TITLE
Problème google home et livebox

### ISSUE THREAD

**Issue by Icemandt** [Aymkdn/assistant-plugins#178]
<!--Bonjour,
assistant-plugins est bien configuré, cependant quand je dis "ok google allume la tv" il me dit ok j'allume la tv mais rien ne se passe.
Voici le détail du fichier start:

assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'bluetooth' (v1.2.2)
[assistant-bluetooth] Plugin chargé et prêt.
[assistant] Chargement du plugin 'control-windows' (v1.0.0)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'livebox' (v1.1.1)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.1)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet

Par avance merci pour votre aide.

**Comment by Aymkdn** [comment]
Bonjour.

Peux-tu suivre les étapes décrites ici stp : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

**Comment by Icemandt** [comment]
Merci pour aide, cependant toujours pareil

![opera instantane_2018-10-21_095734_www pushbullet com](https://user-images.githubusercontent.com/44334750/47264442-cd4ade00-d517-11e8-88ec-0122c706210e.png)

**Comment by Icemandt** [comment]
![opera instantane_2018-10-21_100121_ifttt com](https://user-images.githubusercontent.com/44334750/47264480-595d0580-d518-11e8-88bc-7d9a3d108e61.png)

**Comment by Aymkdn** [comment]
Et rien ne s'affiche dans ta console ? (après `[assistant] Prêt à écouter les commandes via PushBullet`) ?

**Comment by Icemandt** [comment]
[assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'bluetooth' (v1.2.2)
[assistant-bluetooth] Plugin chargé et prêt.
[assistant] Chargement du plugin 'control-windows' (v1.0.0)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'livebox' (v1.1.1)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.1)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'livebox_tv' ]
[assistant] Appelle du plugin 'livebox'

**Comment by Icemandt** [comment]
[assistant] Commande reçue:  [ 'livebox_tv' ]
[assistant] Appelle du plugin 'livebox'
[assistant-livebox] Erreur : { RequestError: Error: connect ETIMEDOUT 192.168.1.1:8080
    at new RequestError (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Programmes\Google home\assistant-plugins\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\Programmes\Google home\assistant-plugins\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 192.168.1.1:8080',
  cause:
   { Error: connect ETIMEDOUT 192.168.1.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.1.1',
     port: 8080 },
  error:
   { Error: connect ETIMEDOUT 192.168.1.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.1.1',
     port: 8080 },
  options:
   { url: 'http://192.168.1.1:8080/remoteControl/cmd?operation=10',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
(node:4236) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 192.168.1.1:8080
    at new RequestError (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Programmes\Google home\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Programmes\Google home\assistant-plugins\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\Programmes\Google home\assistant-plugins\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
(node:4236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Icemandt** [comment]
le roman, c'est du Chinois!!!

**Comment by Aymkdn** [comment]
Plusieurs choses : 

1. L'ordinateur où tourne le programme `assistant-plugins` est-il sur le même réseau local que la Livebox?
2. Si tu ouvres le lien http://192.168.1.1:8080/remoteControl/cmd?operation=10 dans ton navigateur, qu'est-ce que ça donne ?
3. Il faudrait vérifier l'adresse IP de la Livebox en te rendant sur http://livebox/ puis cliquer sur le décodeur, et l'IP devrait s'afficher

**Comment by Icemandt** [comment]
oui le PC est sur le même réseau, j'ai bien vérifié IP de la box, et quand je clic sur le http://192....... j'ai ça
Ce site est inaccessible
192.168.1.1 a mis trop de temps à répondre.

Essayez les suggestions ci-dessous :
Vérifier la connexion
Vérifier le proxy et le pare-feu
Exécutez les diagnostics réseau de Windows
Vérifiez votre connexion internet.
Vérifiez tous les cables, redémarrez votre routeur, modem ou tout autre appareil réseau utilisé.

Permettre à Opera d'accéder au réseau dans les réglages de votre pare-feu ou de votre anti-virus.
S'il est déjà répertorié en tant que programme autorisé à accéder au réseau, essayez de le supprimer de la liste, puis de le rajouter.

Si vous utilisez un serveur proxy…
Vérifiez vos réglages proxy ou contactez votre administrateur réseau pour être sûr que le serveur proxy fonctionne. Si vous ne pensez pas que vous devriez utiliser un serveur proxy : Allez dans le menu principal > Paramètres > Modifier les paramètres du proxy… > Réglages LAN et désélectionnez "Utiliser un serveur proxy pour votre LAN".

**Comment by Icemandt** [comment]
![sans titre 1](https://user-images.githubusercontent.com/44334750/47264965-e015e080-d520-11e8-846e-db38fa5096a5.jpg)

**Comment by Aymkdn** [comment]
L'adresse IP est 192.168.1.10, et non 192.168.1.1

Modifie ta configuration.

**Comment by Icemandt** [comment]
il me semblait que le 0 ne servait à rien, je modifie

**Comment by Icemandt** [comment]
super ça fonctionne, merci beaucoup pour ton aide et ta disponibilité.

**Comment by Icemandt** [comment]
merci à toi, je vais regarder.
