### ISSUE TITLE
Problème de module "debug" avec le plugin Yamaha

### ISSUE THREAD

**Issue by nicopsd** [Aymkdn/assistant-plugins#213]
Hello !
J'ai besoin d'un petit coup de main.
J'ai installé et configuré sans problème le plugin Freebox sur un raspberry. La doc est top, le travail est parfait il suffit de laisser guider ! Merci beaucoup !

Par contre avec le plugin Yamaha j'ai cette erreur au lancement

> ~/assistant-plugins
 $ node index.js
[assistant] Assistant v2.0.8 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'yamaha' (v1.0.2)
{ Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/assistant-plugins/node_modules/assistant-yamaha/yamaha_simpleCommands.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/assistant-plugins/node_modules/assistant-yamaha/yamaha_root.js:1:84)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32) code: 'MODULE_NOT_FOUND' }

J'ai essayé ce plugin seul, avant de mettre celui de la freebox, ou après, mais toujours la même erreur.
J'ai aussi essayé de mettre à jour les modules, ça n'a rien changé.

J'ai installé la dernière version  node-v11.8.0-linux-armv7l
ça viendrait de là ? mais alors pourquoi ça fonctionne avec le plugin freebox ?

Je suis donc à la recherche d'une solution.
Je vais pas m'arrêter sur ma lancé à ce stade ... ce serait cool aussi de piloter l'ampli

**Comment by Aymkdn** [comment]
Je ne suis pas l'auteur de ce plugin. À priori il faut installer le module `debug` (donc `npm install debug`)

Si ça ne fonctionne toujours pas tu peux essayer de demander à l'auteur là : https://github.com/tapsystem/assistant-yamaha/issues

**Comment by nicopsd** [comment]
C'est parfait. Merci pour ta réactivité !
C'était si simple ... j'aurais pu y penser ;-)
