### ISSUE TITLE
Erreur de connexion avec PushBullet

### ISSUE THREAD

**Issue by mikl076** [Aymkdn/assistant-plugins#225]
bonjour !
j'ai un soucis depuis ce midi que je n'arrive pas à résoudre...
les plugins se chargent bien mais arrivé à "connexion avec le flux pushbullet" j'ai cette erreur qui apparaît:
 Global Logs ────────────────────────────────────────────────────────────────────┐│[ 0] index        Mem:  37 MB     ││ index > [assistant] Erreur de connexion avec PushBullet:  { Error: connect       │
│                                  ││ ETIMEDOUT 104.154.164.197:443                                                    │
│                                  ││ index >     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)      │
│                                  ││ index >   errno: 'ETIMEDOUT',                                                    │
│                                  ││ index >   code: 'ETIMEDOUT',                                                     │
│                                  ││ index >   syscall: 'connect',                                                    │
│                                  ││ index >   address: '104.154.164.197',                                            │
│                                  ││ index >   port: 443 }                                                            │
│                                  ││ index > [assistant] (2019-02-07 21:21:04) Le flux avec Pushbullet a été          │
│                                  ││ déconnecté... Tentative de reconnexion...                                        │
│                                  ││                                               

tout marchait bien avant, je n'ai rien touché nulle part ...
je vois vraiment pas d'ou ça peut venir

merci d'avance

**Comment by Aymkdn** [comment]
Bizarre.... T'es sur Windows? Si oui, est-ce que tu n'as pas un antivírus (comme Avast) ou firewall qui bloquerait la connexion ?

**Comment by mikl076** [comment]
oui windows 10 et avast
c'est bizarre avast était déja installé et ça marchait très bien hier

**Comment by Aymkdn** [comment]
Avast est connu pour créer ce problème comme expliqué là https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fréquentes#11-la-console-retourne-lerreur--code-econnreset-errno--econnreset

**Comment by mikl076** [comment]
j'essaie de le désinstaller et je reteste...

**Comment by mikl076** [comment]
oui c'était bien avast le coupable...

merci pour les réponses rapides et désolé du dérangement ;)

**Comment by nusmiaf** [comment]
bonjour , j'ai aussi un problème de communication , la console me dit ça =>

[assistant] Assistant v2.0.12 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'control-windows' (v1.0.2)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'freebox' (v2.0.11)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.6)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-02-27 23:14:01) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-28 02:34:32) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] (2019-02-28 02:34:33) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-28 02:43:34) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Erreur de connexion avec PushBullet:  { Error: connect ETIMEDOUT 1
04.154.164.197:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.154.164.197',
  port: 443 }
[assistant] (2019-02-28 02:43:55) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...

**Comment by Aymkdn** [comment]
@nusmiaf ça m'arrive aussi de temps en temps... Il faut que je me repenche sur le sujet.

**Comment by nusmiaf** [comment]
ok , par contre moi c'est pas de temps en temps c'est tous les jours

**Comment by Aymkdn** [comment]
@nusmiaf j'ai mis en place un patch chez moi. Je le teste pendant quelques jours pour voir, et si c'est concluant je diffuserai.

**Comment by nusmiaf** [comment]
Ok , merci
