### ISSUE TITLE
assistant-plugins en panne depuis quelques semaines

### ISSUE THREAD

**Issue by Jnbond** [Aymkdn/assistant-plugins#252]
Bonjour, 
Voila quelques semaines que les ordres donnés à Alexa pour commander ma freebox ne fonctionne plus. 
L'assistant est installé sur un NAS synology, j'ai donc stoppé celui-ci et relancé en manuel dans une console pour voir les messages : 

 ```
xxx@NAS1: /.../assistant-plugins$ node index.js
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 3 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.12)
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] **### ERREUR : Impossible de récupérer la liste des chaines...**
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] **### Erreur de connexion avec PushBullet**:  { Error: getaddrinfo EAI_AGAIN stream.pushbullet.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: 443 }
[assistant] (2019-06-11 19:55:34) Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...
[assistant] Reconnexion....
[assistant] Erreur de connexion avec PushBullet:  { Error: getaddrinfo EAI_AGAIN stream.pushbullet.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: 443 }
[assistant] (2019-06-11 19:57:14) Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...
```

...
_-Freebox V6 
-Server en V4.0.5.1
-Player en V1.3.16
-node sur synology en V8.9.4_
 
Pourriez-vous m'aider à solutionner le problème ? 
Amicalement

**Comment by Aymkdn** [comment]
Visiblement ton NAS n'a pas accès à internet ou problème de connexion entre ton NAS et internet.

**Comment by Jnbond** [comment]
> Visiblement ton NAS n'a pas accès à internet ou problème de connexion entre ton NAS et internet.

Je te prie de m'excuser, effectivement j'aurais du chercher moins compliqué, les DNS déclarés sur le NAS étaient obsolète.

Merci pour ta réponse rapide et dsl pour la perte de temps. 
Amicalement
