### ISSUE TITLE
Syno arrière plan

### ISSUE THREAD

**Issue by alfa4684** [Aymkdn/assistant-plugins#44]
Bonsoir, j'ai des soucis pour lancer le programme en arrière plan sur Synology ...
Ci dessous la trace.
Install OK à priori en root, mais la commande startup pose problème.
Du coup un redémarrage du syno et on recommence :)
Aymeric, si tu as une idée, suis preneur

login as: admin
admin@192.168.0.3's password:
admin@BelzFamily:~$ cd NodeJS
admin@BelzFamily:~/NodeJS$ cd assistant-plugins
admin@BelzFamily:~/NodeJS/assistant-plugins$ sudo -i
Password:

root@BelzFamily:~# pm2 startup
[PM2][ERROR] Init system not found
/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at CLI.startup (/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183:13)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:627:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:457:21)
    at null._onTimeout (/usr/local/lib/node_modules/pm2/bin/pm2:184:15)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Aymkdn** [comment]
Pas d'idée.... Faut que tu cherches du côté de pm2. C'est totalement indépendant de assistant-plugins ^^

Il existe d'autres modules qui font le même genre de chose, donc cherche de ce côté là aussi, peut-être qu'ils sont plus adaptés à un syno... 

Bon courage, Google est ton meilleur ami 😉

**Comment by Aymkdn** [comment]
https://www.google.fr/search?q=Synology+startup+node+script

**Comment by alfa4684** [comment]
Merci à toi et longue vie à ton plug-in ! Esperons quand meme une integration standard avec la freebox v7 et des APIs natives :)

**Comment by Aymkdn** [comment]
Pour info j'ai fait une documentation dédiée à Synology : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-Synology

Si jamais tu peux regarder et me donner tes commentaires !
