### ISSUE TITLE
Execution de node index.js en tâche de fond sur NAS Synology

### ISSUE THREAD

**Issue by fred3b12** [Aymkdn/assistant-plugins#49]
Bonjour,
Après avoir remplacé NAS vieillissant DS213air par un DS216Play (pour ceux qui ont suivi le précédent épisode :D ) , Je souhaite donc à présent exécuter en tâche de fond mon "node index.js" qui fonctionne parfaitement tant que ma fenêtre ssh est ouvert.

J'ai donc suivit les instruction pour l'installation de PM2 mais sans succès, si vous avez une piste ou un autre moyen, je prends...
<<<<<
fred3b12@JARVIS:/volume1/@GoogleHome/assistant-plugins$ sudo npm install --no-optional pm2 -g
/volume1/@appstore/Node.js_v8/usr/local/bin/pm2 -> /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2
/volume1/@appstore/Node.js_v8/usr/local/bin/pm2-dev -> /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2-dev
/volume1/@appstore/Node.js_v8/usr/local/bin/pm2-docker -> /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2-docker
/volume1/@appstore/Node.js_v8/usr/local/bin/pm2-runtime -> /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2-runtime
+ pm2@2.8.0
added 251 packages in 52.841s
fred3b12@JARVIS:/volume1/@GoogleHome/assistant-plugins$cd /volume1/\@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin

fred3b12@JARVIS:/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin$
fred3b12@JARVIS:/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin$ ./pm2 startup
                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__

                          Community Edition

            Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/

                        -------------

[PM2][ERROR] Init system not found
/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at module.exports.CLI.startup (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/lib/API/Startup.js:183:13)
    at Command.<anonymous> (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2:627:9)
    at Command.listener (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:635:12)
    at Command.parse (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:457:21)
    at Timeout._onTimeout (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin/pm2:184:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)

fred3b12@JARVIS:/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/pm2/bin$

>>>
PS : J'ai aussi tenté en root : même résultat
Merci d'avance

**Comment by Aymkdn** [comment]
En effet il semble qu'il faille utiliser autre chose pour syno https://github.com/Aymkdn/assistant-plugins/issues/44

**Comment by fred3b12** [comment]
Bon et bien n'étant pas expert! (et ne pouvant pas installer screen car le Package pour mon NAS n'est pas encore dispo : et oui nouveau proc. Realtek RTD1296 )

J'ai fait ceci  : 
Un minuscule script appelé   "lanceur-node.sh" avec les droits root que j'ai mis dans le dossier "assistant-plugings contenant : 
#! /bin/sh
cd /volume1/@GoogleHome/assistant-plugins/
node index.js
quit

Que j'ai lancer en crontab qui est dans /ect/crontab  (il va s’exécuter du coup tous les 9 du mois à 18h25 et je changerai la date au besoin... si mon NAS reboot par exemple)

20  18  9	*	*	root    /volume1/@GoogleHome/assistant-plugins/lanceur-node.sh

Et plus besoin de cette fichue fenêtre ssh d'ouvert sur mon NAS 👍  Ha!Ha! Si quelqu'un est d'humeur à faire un script stop start restart, à la bonne heure...

un début de réponse ici...
https://developer.synology.com/developer-guide/integrate_dsm/run_with_system_boot.html

Et Encore Merci Aymeric !!!

**Comment by Aymkdn** [comment]
@fred3b12  tu peux me dire quelle version de node tu as stp sur ton NAS ? (`node -v`).

J'ai installé DS3615xs en machine virtuelle sur mon Windows pour faire des tests... Mais le seul Node proposé est 0.12.6 et j'essaie de voir comment installer une version plus récente.

**Comment by Aymkdn** [comment]
Pour info j'ai fait une documentation dédiée à Synology : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-Synology

Si jamais tu peux regarder et me donner tes commentaires !

**Comment by fred3b12** [comment]
<<@fred3b12 tu peux me dire quelle version de node tu as stp sur ton NAS ? (node -v).

J'ai installé DS3615xs en machine virtuelle sur mon Windows pour faire des tests... Mais le seul Node proposé est 0.12.6 et j'essaie de voir comment installer une version plus récente.>>

Hello, dans les packages Dsm disponibles tu vois seulement la version développée pour ton Nas... Perso après l'achat de mon  nouveau Nas, je ne vois que la 8.2 beta.

**Comment by Aymkdn** [comment]
@fred3b12 oui les packages ne sont pas les plus récents, c'est pourquoi  j'explique dans le tuto comment installer une version plus récente

**Comment by vjooris** [comment]
> Si quelqu'un est d'humeur à faire un script stop start restart, à la bonne heure...
J'ai DSM 6.2, et là tu sais définir des tâches "au démarrage" du serveur.
Donc ta solution combinée à celle-ci , et c'est le paradis !
