### ISSUE TITLE
probléme de conexion avec mon vpn depuis ce soir 

### ISSUE THREAD

**Issue by jeanmichelpaul26** [Aymkdn/assistant-plugins#79]
bonsoir depuis ce soir j'ai ce message d erreur dés que je connecte mon vpn.

Je précise que tout fonctionnait encore il y a 2 joiurs 

je n'y comprend plus rien 

si j'enléve le vpn ( nord Vpn ) tout fonctionne !!!

merci 

```
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.5)
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Récupération des chaines sur free.fr terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)

C:\Users\jean michel\Desktop\assistant-plugins>
```

ci-dessous mon fichier de configuration 
```
{
  "main": {
    "pushbullet_token": "o.S8VW5cxxxH2TTk5dlIVGR1cJShm"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "21822339",
      "player_ip": "192.168.0.32",
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1",
      "app_token": "wy3HAwKFEkseMZxxx9Xk2tdj2CA8uT2S/WzTwjkB6FutXLFchdVyrTlaERVZV"
    },
    "ifttt": {
      "key": "psrMg96xxxreG2QhflVZsUp_e8RWsWrA2ggA8k_tq"
    },
    "notifier": {
      "host": "192.168.0.35"
    }
  }
}
```

**Comment by Aymkdn** [comment]
Je ne sais pas, désolé...

**Comment by jeanmichelpaul26** [comment]
Error: connect ECONNREFUSED 127.0.0.1:443

quel est cet ip?

**Comment by Aymkdn** [comment]
C'est l'adresse locale, donc ton ordinateur.
