### ISSUE TITLE
probleme assistant plugins raspberry

### ISSUE THREAD

**Issue by claudecn13** [Aymkdn/assistant-plugins#85]
bonsoir
j'ai tout installe en suivant vos instructions,j allais lancer le programme "node index.js ",lorsque le raspberry c'est bloqué....
j' ai redemarré mais maintenant quand je lance la commande:
```
pi@raspberrypi:~ $ node index.js
module.js:557
    throw err;
    ^

Error: Cannot find module '/home/pi/index.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

pourtant j ai tout installé assistant pluggins et configuré

  "main": {
    "pushbullet_token": "o.wcO0BpTTQOqyyabWpgZe6UgAH5sdwJ8c"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "27712358",
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1"
    },
    "ifttt": {
      "key": "Bp3PjYIxxx6RwN2VzgnIYD"
```
je dois manquer quelques choses...votre aide sera la bienvenue ,merci d'avances

**Comment by Aymkdn** [comment]
Tu n'es pas dans le bon répertoire. Il te faut aller dans le répertoire `/home/pi/assistang-plugins/`

**Comment by claudecn13** [comment]
cela marche
super ,merci beaucoup...votre aide est précieuse ...
bonne soirée
